"""add_role

Revision ID: 6cbea7abded9
Revises: 
Create Date: 2026-03-20 04:38:33.194458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6cbea7abded9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth_accounts', 'user_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.create_foreign_key(None, 'oauth_accounts', 'users', ['user_id'], ['id'], ondelete='cascade')
    op.add_column('users', sa.Column('role', sa.Enum('user', 'admin', 'superadmin', name='user_role'), nullable=False))
    op.alter_column('users', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.Uuid(),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'oauth_accounts', type_='foreignkey')
    op.alter_column('oauth_accounts', 'user_id',
               existing_type=sa.Uuid(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
