name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: election_service_test

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y curl g++
          curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR="$HOME/.local/bin" sh
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          uv python install 3.11.11
          uv venv
          uv pip install .
          uv pip install --group dev

      - name: Load .env.ci
        run: cp .env.ci .env.test

      - name: Run database migrations
        run: |
          source .venv/bin/activate
          ENV=test alembic upgrade head

      - name: Test with coverage
        run: |
          source .venv/bin/activate
          pytest --cov=app --cov-report=term-missing --cov-report=html
        timeout-minutes: 5

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/

      # Il vérifie que votre code respecte les standards de style (PEP 8) et détecte les erreurs potentielles
      - name: Ruff check
        run: |
          source .venv/bin/activate
          ruff check .

      - name: mypy
        run: |
          source .venv/bin/activate
          mypy --config-file mypy.ini .
