"""Add program position slogan priorities to candidates

Revision ID: 353500238530
Revises: 804ea2ee06ec
Create Date: 2026-03-08 14:28:03.188946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '353500238530'
down_revision: Union[str, None] = '804ea2ee06ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('program', sa.String(length=200), nullable=True))
    op.add_column('candidates', sa.Column('position', sa.String(length=120), nullable=True))
    op.add_column('candidates', sa.Column('slogan', sa.String(length=300), nullable=True))
    op.add_column('candidates', sa.Column('priorities', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'candidates', 'elections', ['election_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'votes', 'elections', ['election_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'votes', 'candidates', ['candidate_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'priorities')
    op.drop_column('candidates', 'slogan')
    op.drop_column('candidates', 'position')
    op.drop_column('candidates', 'program')
    # ### end Alembic commands ###
