"""description

Revision ID: 62b827889979
Revises: 353500238530
Create Date: 2026-03-08 14:39:23.103068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b827889979'
down_revision: Union[str, None] = '353500238530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'candidates', 'elections', ['election_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'votes', 'candidates', ['candidate_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'votes', 'elections', ['election_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    # ### end Alembic commands ###
