"""add_approval_status_to_candidates

Revision ID: 699595c8e1c1
Revises: 62b827889979
Create Date: 2026-04-06 02:26:45.745804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '699595c8e1c1'
down_revision: Union[str, None] = '62b827889979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('approval_status', sa.Enum('pending', 'approved', 'rejected', name='approvalstatus'), nullable=False))
    op.create_index(op.f('ix_candidates_approval_status'), 'candidates', ['approval_status'], unique=False)
    op.create_foreign_key(None, 'candidates', 'elections', ['election_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'votes', 'elections', ['election_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'votes', 'candidates', ['candidate_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_index(op.f('ix_candidates_approval_status'), table_name='candidates')
    op.drop_column('candidates', 'approval_status')
    # ### end Alembic commands ###
