"""Add email to election_users

Revision ID: 804ea2ee06ec
Revises: 52bb61a1a135
Create Date: 2026-03-08 13:57:24.141147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '804ea2ee06ec'
down_revision: Union[str, None] = '52bb61a1a135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'candidates', 'elections', ['election_id'], ['id'], ondelete='CASCADE')
    op.add_column('election_users', sa.Column('email', sa.String(length=320), nullable=False))
    op.create_foreign_key(None, 'votes', 'elections', ['election_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'votes', 'candidates', ['candidate_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_column('election_users', 'email')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    # ### end Alembic commands ###
